package dao;

import java.sql.*;

import org.apache.commons.dbutils.DbUtils;

public class DAO {
	private Connection connection;

	public DAO() {
		try {
			Class.forName("org.hsqldb.jdbcDriver");
		} catch (ClassNotFoundException e) {
			throw new RuntimeException(e);
		}

		try {
			String db = "${user.home}/i377/Team02d/db;shutdown=true";
			connection = DriverManager.getConnection("jdbc:hsqldb:" + db, "sa",
					"");
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public Connection getConnection() {
		return connection;
	}

	public void createTables() {
		dropTables();
		createTestTable();
	}

	public boolean executeSQL(String sql) {
		Statement st = null;
		try {
			st = connection.createStatement();
			return st.execute(sql);
		} catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			DbUtils.closeQuietly(st);
		}
	}

	public int executeUpdateSQL(String sql) {
		Statement st = null;
		try {
			st = connection.createStatement();
			return st.executeUpdate(sql);
		} catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			DbUtils.closeQuietly(st);
		}
	}

	private void dropTables() {
		executeSQL("DROP TABLE TestName IF EXISTS");
	}

	private void createTestTable() {
		executeSQL("CREATE TABLE TestName ( "
				+ "ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,"
				+ "Name                 VARCHAR(32) NOT NULL,"
				+ "PRIMARY KEY (ID)" + ")");
	}

	public void insertDummyData() {
		insertDummyDataToTestName();
	}

	private void insertDummyDataToTestName() {
		executeUpdateSQL("INSERT INTO TestName " + "(Name) " + "VALUES "
				+ "('Mari')," + "('Jüri')," + "('Miku')," + "('Manni')");
	}
}
